const SUPABASE_URL = "https://tqfocdktvjuwoiyfgesb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZm9jZGt0dmp1d29peWZnZXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5MDg0NTIsImV4cCI6MjEwNTQ4NDQ1Mn0.8TW4fQCQHc4c_xTNBEwOK3lSC9HYCbkTbfXuYQB-S8g";
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = (id) => document.getElementById(id);
const state = { user: null, profile: null, signup: false, likes: {}, wall: [] };
const headlines = ["Quiet things, written down.","Someone left the window open.","The hour prefers short sentences.","Nothing urgent. Still worth keeping.","A room with the lights half-down.","Notes that would not sit still.","The wall is listening, not ranking."];
function hourStart(d = new Date()) { const x = new Date(d); x.setMinutes(0, 0, 0); return x; }
function hourKey(d = new Date()) { return hourStart(d).toISOString(); }
function hash(str) { let h = 2166136261; for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); } return Math.abs(h); }
function fmtTime(d) { return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }
function fmtWhen(iso) { const d = new Date(iso); return d.toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
function escapeHtml(s) { return String(s ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
function tick() { const now = new Date(); $("clock").textContent = fmtTime(now); const next = new Date(hourStart(now).getTime() + 3600000); const ms = next - now; const m = Math.floor(ms / 60000); const s = Math.floor((ms % 60000) / 1000); $("until").textContent = `${m}m ${String(s).padStart(2, "0")}s to turnover`; $("editionSlot").textContent = `Hour ${String(now.getHours()).padStart(2, "0")}:00`; }
function noteCard(n, mine) { const rot = ((hash(n.id) % 14) - 7) / 10; const el = document.createElement("article"); el.className = "note"; el.style.transform = `rotate(${rot}deg)`; const liked = !!state.likes[n.id]; el.innerHTML = `<h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.body)}</p><div class="row"><span class="chip">${n.is_public ? "public" : "desk"}</span><span class="meta">${fmtWhen(n.created_at)}</span></div>`; const row = el.querySelector(".row"); if (n.is_public) { const like = document.createElement("button"); like.className = "tiny"; like.textContent = liked ? "Kept" : "Keep"; like.onclick = () => toggleLike(n.id); row.prepend(like); } if (mine) { const btn = document.createElement("button"); btn.className = "tiny"; btn.textContent = n.is_public ? "Make private" : "Make public"; btn.onclick = () => togglePublic(n); const del = document.createElement("button"); del.className = "tiny"; del.textContent = "Delete"; del.onclick = () => removeNote(n.id); row.prepend(btn); row.append(del); } return el; }
function renderWall(list) { const grid = $("wallGrid"); grid.innerHTML = ""; if (!list.length) { grid.innerHTML = `<p class="empty">Nothing matches this hour.</p>`; return; } list.forEach((n, i) => { const card = noteCard(n, state.user && n.user_id === state.user.id); card.style.animationDelay = `${i * 45}ms`; grid.append(card); }); }
async function loadLikes() { const { data } = await sb.from("note_likes").select("note_id"); state.likes = {}; (data || []).forEach((r) => { if (state.user && true) state.likes[r.note_id] = true; }); }
async function loadWall() { const { data, error } = await sb.from("notes").select("id,title,body,is_public,created_at,user_id").eq("is_public", true).order("created_at", { ascending: false }).limit(60); const grid = $("wallGrid"); if (error) { grid.innerHTML = `<p class="empty">${escapeHtml(error.message)}</p>`; return []; } state.wall = data || []; if (!state.wall.length) { grid.innerHTML = `<p class="empty">The wall is empty. The first public note sets the tone.</p>`; return []; } renderWall(state.wall); return state.wall; }
async function loadDesk() { const grid = $("deskGrid"); const form = $("noteForm"); if (!state.user) { form.classList.add("hidden"); $("deskHint").textContent = "Sign in to keep a private stack. Public notes appear on the wall."; grid.innerHTML = ""; return; } form.classList.remove("hidden"); $("deskHint").textContent = `Signed in as ${state.profile?.handle || state.user.email}. Private stays private.`; const { data, error } = await sb.from("notes").select("id,title,body,is_public,created_at,user_id").eq("user_id", state.user.id).order("created_at", { ascending: false }); grid.innerHTML = ""; if (error) { grid.innerHTML = `<p class="empty">${escapeHtml(error.message)}</p>`; return; } if (!data?.length) { grid.innerHTML = `<p class="empty">Your desk is clear.</p>`; return; } data.forEach((n) => grid.append(noteCard(n, true))); }
async function stampHour(publicNotes) { const key = hourKey(); const { data: existing } = await sb.from("hours").select("*").eq("slot", key).maybeSingle(); let featured = null; if (publicNotes.length) featured = publicNotes[hash(key) % publicNotes.length]; $("headline").textContent = existing?.headline || headlines[hash(key) % headlines.length]; $("lede").textContent = existing?.editorial || (featured ? "A public note is sitting at the front of the room until the clock turns." : "Write something. Keep it in your desk, or mark it public and let the next hour carry it."); const box = $("featured"); const card = $("featuredCard"); if (featured) { box.classList.remove("hidden"); card.innerHTML = `<h3>${escapeHtml(featured.title)}</h3><p>${escapeHtml(featured.body)}</p><p class="meta">Held until the hour ends</p>`; } else box.classList.add("hidden"); if (!existing && state.user) { await sb.from("hours").insert({ slot: key, headline: headlines[hash(key + "h") % headlines.length], editorial: featured ? featured.title : "An empty hour. That is allowed.", featured_note_id: featured?.id || null }); } }
async function loadHours() { const { data } = await sb.from("hours").select("*").order("slot", { ascending: false }).limit(24); const list = $("hourList"); list.innerHTML = ""; if (!data?.length) { list.innerHTML = `<li class="empty">No stamped hours yet. Stay through a turnover.</li>`; return; } data.forEach((h) => { const li = document.createElement("li"); li.innerHTML = `<strong>${escapeHtml(h.headline)}</strong><span class="meta">${fmtWhen(h.slot)} — ${escapeHtml(h.editorial || "")}</span>`; list.append(li); }); }
async function togglePublic(n) { await sb.from("notes").update({ is_public: !n.is_public, updated_at: new Date().toISOString() }).eq("id", n.id); await refresh(); }
async function removeNote(id) { await sb.from("notes").delete().eq("id", id); await refresh(); }
async function toggleLike(id) { if (!state.user) { $("modal").classList.remove("hidden"); return; } if (state.likes[id]) { await sb.from("note_likes").delete().eq("note_id", id).eq("user_id", state.user.id); } else { await sb.from("note_likes").insert({ note_id: id, user_id: state.user.id }); } await refresh(); }
async function ensureProfile() { if (!state.user) return; const { data } = await sb.from("profiles").select("*").eq("id", state.user.id).maybeSingle(); if (data) { state.profile = data; return; } const base = (state.user.email || "member").split("@")[0].replace(/[^a-z0-9]/gi, "").toLowerCase() || "member"; const handle = base + state.user.id.replace(/-/g, "").slice(0, 4); await sb.from("profiles").insert({ id: state.user.id, handle, display_name: base }); state.profile = { handle, display_name: base }; }
async function refresh() { await loadLikes(); const publicNotes = await loadWall(); await stampHour(publicNotes); await loadDesk(); await loadHours(); }
async function setSession(session) { state.user = session?.user || null; $("authBtn").textContent = state.user ? "Sign out" : "Sign in"; if (state.user) await ensureProfile(); await refresh(); }
$("authBtn").onclick = async () => { if (state.user) { await sb.auth.signOut(); return; } $("modal").classList.remove("hidden"); };
$("closeModal").onclick = () => $("modal").classList.add("hidden");
$("toggleMode").onclick = () => { state.signup = !state.signup; $("modalTitle").textContent = state.signup ? "Create account" : "Sign in"; $("toggleMode").textContent = state.signup ? "Have an account? Sign in" : "Need an account? Create one"; };
$("authForm").onsubmit = async (e) => { e.preventDefault(); const fd = new FormData(e.target); const email = fd.get("email"); const password = fd.get("password"); $("authMsg").textContent = ""; $("authMsg").classList.remove("err"); let error; if (state.signup) { ({ error } = await sb.auth.signUp({ email, password })); if (!error) $("authMsg").textContent = "Account created. If email confirmation is on, check your inbox, then sign in."; } else { ({ error } = await sb.auth.signInWithPassword({ email, password })); } if (error) { $("authMsg").textContent = error.message; $("authMsg").classList.add("err"); return; } if (!state.signup) $("modal").classList.add("hidden"); };
$("noteForm").onsubmit = async (e) => { e.preventDefault(); if (!state.user) return; const fd = new FormData(e.target); const { error } = await sb.from("notes").insert({ user_id: state.user.id, title: String(fd.get("title")).trim(), body: String(fd.get("body")).trim(), is_public: fd.get("is_public") === "on" }); if (error) { alert(error.message); return; } e.target.reset(); await refresh(); };
$("wallSearch").addEventListener("input", (e) => { const q = e.target.value.toLowerCase().trim(); if (!q) return renderWall(state.wall); renderWall(state.wall.filter((n) => `${n.title} ${n.body}`.toLowerCase().includes(q))); });
document.querySelectorAll("[data-go]").forEach((b) => { b.onclick = () => document.getElementById(b.dataset.go)?.scrollIntoView({ behavior: "smooth" }); });
const cur = $("cursor"); window.addEventListener("pointermove", (e) => { cur.style.left = e.clientX + "px"; cur.style.top = e.clientY + "px"; });
sb.auth.onAuthStateChange((_e, session) => setSession(session));
sb.auth.getSession().then(({ data }) => setSession(data.session));
tick(); setInterval(tick, 1000);
let lastHour = hourKey();
setInterval(() => { const nowKey = hourKey(); if (nowKey !== lastHour) { lastHour = nowKey; document.body.animate([{ filter: "contrast(1)" }, { filter: "contrast(1.15) saturate(1.1)" }, { filter: "contrast(1)" }], { duration: 900 }); refresh(); } }, 4000);
